import type { PaidPlanInfo } from '../types';

export const PAID_PLANS: PaidPlanInfo[] = [
  {
    id: 'PLUS',
    name: 'PLUS PLAN',
    badge: 'ACCELERATOR',
    starsPrice: 99,
    uzsPrice: '15,000 UZS',
    validityDays: 30,
    callLimit: 10,
    maxDurationMinutes: 30,
    recordingsLimit: 3,
    retentionDays: 7,
    queuePriority: 'Standard Priority',
    accentColor: 'text-cyan-400',
    borderColor: 'border-cyan-500/40 hover:border-cyan-400',
    bgGlow: 'from-cyan-950/40 via-slate-900/80 to-slate-900',
    description: 'Essential toolkit for focused IELTS Speaking practice routines.',
    features: [
      '10 Practice Calls / month',
      '30 min Max Duration per call',
      '3 Cloud Audio Recordings',
      '7 Days Audio Retention',
      'Standard Matchmaking Queue',
      'Single Learner Account',
    ],
  },
  {
    id: 'PRO',
    name: 'PRO PLAN',
    badge: 'MOST POPULAR',
    starsPrice: 349,
    uzsPrice: '55,000 UZS',
    validityDays: 30,
    callLimit: 25,
    maxDurationMinutes: 60,
    recordingsLimit: 7,
    retentionDays: 30,
    queuePriority: 'High Priority',
    accentColor: 'text-purple-400',
    borderColor: 'border-purple-500/50 hover:border-purple-400',
    bgGlow: 'from-purple-950/50 via-slate-900/90 to-slate-900',
    description: 'Targeted for ambitious learners aiming for Band 7.5+ mastery.',
    features: [
      '25 Practice Calls / month',
      '60 min Max Duration per call',
      '7 Cloud Audio Recordings',
      '30 Days Audio Retention',
      'Fast-Track High Queue Priority',
      'Single Learner Account',
    ],
  },
  {
    id: 'BOSS',
    name: 'BOSS PLAN',
    badge: 'UNLIMITED POWER',
    starsPrice: 899,
    uzsPrice: '149,000 UZS',
    validityDays: 30,
    callLimit: 50,
    maxDurationMinutes: 90,
    recordingsLimit: 15,
    retentionDays: 90,
    queuePriority: 'VIP Priority',
    accentColor: 'text-amber-400',
    borderColor: 'border-amber-500/50 hover:border-amber-400',
    bgGlow: 'from-amber-950/50 via-slate-900/90 to-slate-900',
    description: 'Comprehensive immersion package with maximum call limits.',
    features: [
      '50 Practice Calls / month',
      '90 min Extended Call Duration',
      '15 Cloud Audio Recordings',
      '90 Days Audio Retention',
      'VIP Matchmaking Priority',
      'Single Learner Account',
    ],
  },
];
